---

- name: Install Python 3
  apt:
    name: python3
    update_cache: true

- name: Install Python Virtual Enviroment
  apt:
    name: python3-venv

- name: Install Pip
  apt:
    name: python3-pip


- name: Install Sphinx
  pip: 
    name: Sphinx
    executable: pip3

- name: Install Read The Docs Theme
  pip: 
    name: sphinx_rtd_theme
    executable: pip3
...
